# BOOK : 도서 정보
# AUTHOR : 저자의 정보
# BOOK_SALES : 날짜별 도서 판매량

SELECT
    BOOK.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM
    BOOK AS BOOK
    JOIN
    AUTHOR AS AUTHOR
    ON 
    BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN
    BOOK_SALES AS SALES
    ON 
    BOOK.BOOK_ID = SALES.BOOK_ID
WHERE
    YEAR(SALES.SALES_DATE) = 2022
    AND
    MONTH(SALES.SALES_DATE) = 1
GROUP BY
    BOOK.AUTHOR_ID,
    BOOK.CATEGORY
ORDER BY
    AUTHOR.AUTHOR_ID,
    BOOK.CATEGORY DESC


# SELECT 
#   A.AUTHOR_ID, 
#   B.AUTHOR_NAME, 
#   A.CATEGORY,
#   SUM(C.SALES * A.PRICE) AS TOTAL_SALES
# FROM 
#   BOOK A
# JOIN 
#   AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
# JOIN 
#   BOOK_SALES C ON C.BOOK_ID = A.BOOK_ID
# WHERE 
#   C.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
# GROUP BY 
#   A.AUTHOR_ID, 
#   A.CATEGORY
# ORDER BY 
#   A.AUTHOR_ID ASC, 
#   A.CATEGORY DESC