-- 코드를 입력하세요
# SELECT음식종류,ID,식당이름,즐겨찾기수
# GROUP BY 음식종류
# WHERE 즐겨찾기수가 가장 많은 식당.
# ORDER BY 음식종류DESC
SELECT FOOD_TYPE, REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) IN(
SELECT FOOD_TYPE, MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE) 
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC