# CAR_RENTAL_COMPANY_)CAR : 대여 중인 자동차의 정보
# CAR_HISTORY : 대여 기록 정보
# CAR DISCOUNT : 종류 별 할인 정책 정보

# 종류가 세단 OR SUV
# 특정 날까까지 대여 가능
# 할인율을 고려한 30일간의 대여 금액이 50 이상 200미만

SELECT 
    DISTINCT CAR.CAR_ID,
    CAR.CAR_TYPE,
    ROUND(30 * CAR.DAILY_FEE * (100 - DISCOUNT.DISCOUNT_RATE) / 100) AS FEE
    
FROM
    CAR_RENTAL_COMPANY_CAR AS CAR
    JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    ON CAR.CAR_ID = HISTORY.CAR_ID
    JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT
    ON CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
WHERE
    CAR.CAR_TYPE IN ('세단','SUV')
    AND
    CAR.CAR_ID NOT IN
                        (
                             SELECT CAR_ID
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
           WHERE ('2022-11-01 00:00:00' BETWEEN START_DATE AND END_DATE)
              OR ('2022-11-30 23:59:59' BETWEEN START_DATE AND END_DATE)
                        )
    AND
    DURATION_TYPE = '30일 이상'
    AND
    30 * CAR.DAILY_FEE * (100 - DISCOUNT.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 1999999
GROUP BY
    CAR.CAR_ID
    
ORDER BY
    FEE DESC,
    CAR.CAR_TYPE ASC,
    CAR.CAR_ID DESC