# 두 테이블 조인 BY USER_ID
# SELECT
#     DISTINCT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS

# FROM
#     USER_INFO A
#     JOIN
#     ONLINE_SALE B
#     ON A.USER_ID = B.USER_ID
# WHERE
#     A.GENDER IS NOT NULL
# GROUP BY
#     YEAR,MONTH,GENDER
# ORDER BY
#     YEAR,
#     MONTH,
#     GENDER

SELECT 
    DISTINCT YEAR(SALE.SALES_DATE) AS YEAR,
    MONTH(SALE.SALES_DATE) AS MONTH,
    USER.GENDER,
    COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM
    USER_INFO AS USER
    JOIN
    ONLINE_SALE AS SALE
    ON USER.USER_ID = SALE.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY
    YEAR(SALE.SALES_DATE),
    MONTH(SALE.SALES_DATE),
    USER.GENDER
    
# ORDER BY
#     YEAR ASC, MONTH ASC, GENDER ASC