# -- 코드를 입력하세요
# -- 상품코드, 매출액 (판매량 * 가격)
# SELECT A.PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
# FROM PRODUCT A 
# INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
# GROUP BY A.PRODUCT_CODE
# ORDER BY SALES DESC, A.PRODUCT_CODE ASC


















SELECT P.PRODUCT_CODE, SUM(O.SALES_AMOUNT * P.PRICE) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC