-- 코드를 입력하세요
# SELECT ROUND(AVG(DAILY_FEE),0) AS AVERAGE_FEE # ROUND : 반올림, AVG:평균, 컬럼명 새로.
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = "SUV"

SELECT ROUND(AVG(DAILY_FEE),0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'