-- 코드를 입력하세요
# 종류가 세단
# 10월에 대여 시작 기록
# 중복 제거
# ID기준 내림차순
SELECT DISTINCT(B.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON
A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '세단' AND MONTH(B.START_DATE) = 10 
ORDER BY B.CAR_ID DESC
